macro(array2d_generator includename structname typedesc typename_lowercase typename type)
  SET (ARRAY2DINCLUDENAME ${includename})
  SET (ARRAY2DSTRUCTNAME ${structname})
  SET (ARRAY2DTYPEDESC ${typedesc})
  SET (LARRAY2DTYPENAME ${typename_lowercase})
  SET (ARRAY2DTYPENAME ${typename})
  SET (ARRAY2DTYPE ${type})
  configure_file(${SYSTEM_LAYER_SOURCES_DIR}/templates/array2d_template.h  ${OPENROX_BINARY_DIR}/generated/array2d_${LARRAY2DTYPENAME}.h @ONLY)
  configure_file(${SYSTEM_LAYER_SOURCES_DIR}/templates/array2d_template.c  ${OPENROX_BINARY_DIR}/generated/array2d_${LARRAY2DTYPENAME}.c @ONLY)
endmacro()

array2d_generator ("<system/memory/datatypes.h>" "struct" 	"ROX_TYPE_DOUBLE" "double" "Double" "Rox_Double")
array2d_generator ("<system/memory/datatypes.h>" "struct" 	"ROX_TYPE_FLOAT" 	"float" 	"Float" 	"Rox_Float")
array2d_generator ("<system/memory/datatypes.h>" "struct"	"ROX_TYPE_UCHAR" 	"uchar" 	"Uchar" 	"Rox_Uchar")
array2d_generator ("<system/memory/datatypes.h>" "struct" 	"ROX_TYPE_UINT" 	"uint" 	"Uint" 	"Rox_Uint")
array2d_generator ("<system/memory/datatypes.h>" "struct" 	"ROX_TYPE_SINT" 	"sint" 	"Sint" 	"Rox_Sint")
array2d_generator ("<system/memory/datatypes.h>" "struct" 	"ROX_TYPE_SLINT" 	"slint" 	"Slint" 	"Rox_Slint")
array2d_generator ("<system/memory/datatypes.h>" "struct" 	"ROX_TYPE_USHORT" "ushort" "Ushort" "Rox_Ushort")
array2d_generator ("<system/memory/datatypes.h>" "struct" 	"ROX_TYPE_SSHORT" "sshort" "Sshort" "Rox_Sshort")

array2d_generator ("<baseproc/geometry/point/point2d_struct.h>" "struct" "ROX_TYPE_POINT2D_FLOAT"  "point2d_float"   "Point2D_Float"  "Rox_Point2D_Float_Struct")
array2d_generator ("<baseproc/geometry/point/point2d_struct.h>" "struct" "ROX_TYPE_POINT2D_DOUBLE" "point2d_double"  "Point2D_Double" "Rox_Point2D_Double_Struct")
array2d_generator ("<baseproc/geometry/point/point2d_struct.h>" "struct" "ROX_TYPE_POINT2D_SSHORT" "point2d_sshort"  "Point2D_Sshort" "Rox_Point2D_Sshort_Struct")
array2d_generator ("<baseproc/geometry/point/point3d_struct.h>" "struct" "ROX_TYPE_POINT3D_FLOAT"  "point3d_float"   "Point3D_Float"  "Rox_Point3D_Float_Struct")
array2d_generator ("<baseproc/geometry/point/point3d_struct.h>" "struct" "ROX_TYPE_POINT3D_DOUBLE" "point3d_double"  "Point3D_Double" "Rox_Point3D_Double_Struct")