install(FILES ${OPENROX_BINARY_DIR}/generated/openrox.h                                           DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/config.h                                            DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/array2d_uchar.h                                     DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/array2d_point2d_sshort.h                            DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/array2d_point2d_float.h                             DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/array2d_double.h                                    DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/array2d_uint.h                                      DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/array2d_float.h                                     DESTINATION inc/generated/)

install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_double.h                                     DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_sint.h                                       DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_uint.h                                       DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_segment_point.h                              DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_double.h                                     DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_quad_segment2d.h                             DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_rect_sint_struct.h                           DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_quad.h                                       DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_quad_segment2d.h                             DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_orientedimagepoint.h                         DESTINATION inc/generated/)

install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_point2d_float.h                              DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_point3d_float.h                              DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_uint.h                                       DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_quad.h                                       DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_ehid_point.h                                 DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_ehid_dbnode.h                                DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_ehid_match.h                                 DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_orientedimagepoint.h                         DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_sraiddesc.h                                  DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dynvec_ehid_dbindex.h                               DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/objset_ehid_target.h                                DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/objset_dynvec_sraid_feature.h                       DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/objset_dynvec_orientedimagepoint.h                  DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/objset_photoframe.h                                 DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/objset_array2d_double.h                             DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/objset_template_ident.h                             DESTINATION inc/generated/)
install(FILES ${OPENROX_BINARY_DIR}/generated/dllist_quadtree_item.h                              DESTINATION inc/generated/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/system/memory/datatypes.h                             DESTINATION inc/system/memory/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/memory/pstdint.h                               DESTINATION inc/system/memory/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/memory/memory.h                                DESTINATION inc/system/memory/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/memory/array2d.h                               DESTINATION inc/system/memory/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/system/memory/array.h                                 DESTINATION inc/system/memory/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/arch/compiler.h                                DESTINATION inc/system/arch/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/arch/platform.h                                DESTINATION inc/system/arch/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/arch/platform_ansi.h                           DESTINATION inc/system/arch/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/time/timer.h                                   DESTINATION inc/system/time/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/system/errors/errors.h                                DESTINATION inc/system/errors/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/inout/drawing/color.h                                 DESTINATION inc/inout/drawing/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/baseproc/geometry/points/point_def.h                  DESTINATION inc/baseproc/geometry/points/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/baseproc/geometry/rectangle/rectangle_def.h           DESTINATION inc/baseproc/geometry/rectangle/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/identification/photoframe.h                      DESTINATION inc/core/identification/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/sraid/sraiddesc_obj.h       DESTINATION inc/core/features/descriptors/sraid/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid.h                 DESTINATION inc/core/features/descriptors/ehid/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_compiler.h        DESTINATION inc/core/features/descriptors/ehid/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_database.h        DESTINATION inc/core/features/descriptors/ehid/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_matcher.h         DESTINATION inc/core/features/descriptors/ehid/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_dbindex.h         DESTINATION inc/core/features/descriptors/ehid/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_searchtree.h      DESTINATION inc/core/features/descriptors/ehid/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_dbnode_obj.h      DESTINATION inc/core/features/descriptors/ehid/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_match_obj.h       DESTINATION inc/core/features/descriptors/ehid/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_target_obj.h      DESTINATION inc/core/features/descriptors/ehid/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_dbindex_obj.h     DESTINATION inc/core/features/descriptors/ehid/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/descriptors/ehid/ehid_obj.h             DESTINATION inc/core/features/descriptors/ehid/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/detectors/segment/segmentpoint_obj.h    DESTINATION inc/core/features/detectors/segment/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/detectors/quad/quad_detection.h         DESTINATION inc/core/features/detectors/quad/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/features/detectors/quad/quad_detection_object.h  DESTINATION inc/core/features/detectors/quad/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/occupancy/quadtree_ref.h                         DESTINATION inc/core/occupancy/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/occupancy/quadtree_item_obj.h                    DESTINATION inc/core/occupancy/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/core/inertial/sensor/imu.h                            DESTINATION inc/core/inertial/sensor/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/inertial/frame/frame.h                           DESTINATION inc/core/inertial/frame/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/inertial/measure/inertial_measure.h              DESTINATION inc/core/inertial/measure/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/inertial/measure/inertial_measure_buffer.h       DESTINATION inc/core/inertial/measure/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/inertial/observer/inertial_observer.h            DESTINATION inc/core/inertial/observer/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/identification/templateident.h                   DESTINATION inc/core/identification/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/identification/templateident_se3.h               DESTINATION inc/core/identification/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/identification/multiident.h                      DESTINATION inc/core/identification/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/identification/dbident_se3.h                     DESTINATION inc/core/identification/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/core/pyramid/pyramid_uchar.h                          DESTINATION inc/core/pyramid/)

install(FILES ${OPENROX_SOURCE_DIR}/sources/user/image/image.h                                    DESTINATION inc/user/image/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/image/image_display.h                            DESTINATION inc/user/image/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/maths/matrix.h                                   DESTINATION inc/user/maths/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/maths/matse3.h                                   DESTINATION inc/user/maths/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/maths/matsl3.h                                   DESTINATION inc/user/maths/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/sensor/camera/camera.h                           DESTINATION inc/user/sensor/camera/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/sensor/inertial/inertial.h                       DESTINATION inc/user/sensor/inertial/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/license/license_activation_public.h              DESTINATION inc/user/license/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/license/license.h                                DESTINATION inc/user/license/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/model/model_singleplane.h                        DESTINATION inc/user/model/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/identification/photoframe/ident_photoframe_se3.h DESTINATION inc/user/identification/photoframe/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/identification/texture/ident_texture_se3.h       DESTINATION inc/user/identification/texture/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/identification/database/ident_database_se3.h     DESTINATION inc/user/identification/database/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/identification/database/database_item.h          DESTINATION inc/user/identification/database/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/identification/database/database.h               DESTINATION inc/user/identification/database/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/odometry/plane/odometry_singleplane.h            DESTINATION inc/user/odometry/plane/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/odometry/plane/odometry_singleplane_params.h     DESTINATION inc/user/odometry/plane/)
install(FILES ${OPENROX_SOURCE_DIR}/sources/user/inertial/odometry_inertial_observer.h            DESTINATION inc/user/inertial/)
